/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  EntropyErrors,
  EntropyErrorsInterface,
} from "../../../contracts/interfaces/EntropyErrors";

const _abi = [
  {
    inputs: [],
    name: "AssertionFailure",
    type: "error",
  },
  {
    inputs: [],
    name: "BlockhashUnavailable",
    type: "error",
  },
  {
    inputs: [],
    name: "IncorrectRevelation",
    type: "error",
  },
  {
    inputs: [],
    name: "InsufficientFee",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidRevealCall",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidUpgradeMagic",
    type: "error",
  },
  {
    inputs: [],
    name: "NoSuchProvider",
    type: "error",
  },
  {
    inputs: [],
    name: "NoSuchRequest",
    type: "error",
  },
  {
    inputs: [],
    name: "OutOfRandomness",
    type: "error",
  },
  {
    inputs: [],
    name: "ProviderAlreadyRegistered",
    type: "error",
  },
  {
    inputs: [],
    name: "Unauthorized",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212203aff532b5085c18861fc6ef65232cfeacdfd63a7036f4c77a00b03c035d7f2e664736f6c63430008180033";

type EntropyErrorsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: EntropyErrorsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class EntropyErrors__factory extends ContractFactory {
  constructor(...args: EntropyErrorsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      EntropyErrors & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): EntropyErrors__factory {
    return super.connect(runner) as EntropyErrors__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EntropyErrorsInterface {
    return new Interface(_abi) as EntropyErrorsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): EntropyErrors {
    return new Contract(address, _abi, runner) as unknown as EntropyErrors;
  }
}
