/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IVerifyWorldIDInterface extends Interface {
  getFunction(
    nameOrSignature: "isVerifiedHuman" | "verifyHuman"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isVerifiedHuman",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyHuman",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "isVerifiedHuman",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyHuman",
    data: BytesLike
  ): Result;
}

export interface IVerifyWorldID extends BaseContract {
  connect(runner?: ContractRunner | null): IVerifyWorldID;
  waitForDeployment(): Promise<this>;

  interface: IVerifyWorldIDInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isVerifiedHuman: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  verifyHuman: TypedContractMethod<
    [
      signal: AddressLike,
      root: BigNumberish,
      nullifierHash: BigNumberish,
      proof: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isVerifiedHuman"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "verifyHuman"
  ): TypedContractMethod<
    [
      signal: AddressLike,
      root: BigNumberish,
      nullifierHash: BigNumberish,
      proof: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
