/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ethaySol from "./Ethay.sol";
export type { ethaySol };
import type * as usdtSol from "./USDT.sol";
export type { usdtSol };
import type * as worldIdSol from "./WorldID.sol";
export type { worldIdSol };
import type * as interfaces from "./interfaces";
export type { interfaces };
